name: Deploy a Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 游꿀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 游뚴 Obtener c칩digo m치s reciente
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 游늭 Sincronizar archivos FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 217.196.57.131  # IP sacada de tu imagen
        username: u676347305.gustavogravagna.com  # Usuario sacado de tu imagen
        password: ${{ secrets.FTP_PASSWORD }} # Lee la contrase침a segura
        # IMPORTANTE: Confirma que esta ruta exista en tu Hostinger o el deploy fallar치
        server-dir: ./dominioprueba/wp-content/themes/child-theme/
