name: Deploy a Cliente MX (SFTP)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy MX
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Obtener código más reciente
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📂 Sincronizar archivos SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: access-5015726610.ud-webspace.de
          username: a124214
          password: (Cr3at3b1u3.MX!!)
          port: 22
          # En esta acción, remote_path define dónde se suben los archivos
          remote_path: mx/wp-content/themes/child-theme/
